--1. INFORMATION_SCHEMA.COLUMNS

    --a. VIEWING THE DATA TYPES OF COLUMNS;
SELECT COLUMN_NAME, DATA_TYPE FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'titanic';


    --b. VIEWING THE NUMBER OF ROWS AND COLUMNS
SELECT
 (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE table_name = 'titanic') AS number_of_columns,
 (SELECT COUNT(*) FROM titanic) AS number_of_rows


    --c. VIEWING DETAİLS OF A SPECIFIC COLUMN
SELECT *
FROM INFORMATION_SCHEMA.COLUMNS WHERE table_name = 'titanic' AND column_name = 'Age';


--2. INFORMATION_SCHEMA.TABLES

    --a. VIEWING DETAILS OF A SPECIFIC TABLE;
SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'titanic'

    --b. VIEWING THE NAME AND SCHEMA OF A SPECIFIC TABLE
SELECT table_name, table_schema FROM INFORMATION_SCHEMA.TABLES 
WHERE table_name = 'titanic'


--3. INFORMATION_SCHEMA.SCHEMATA

    --a. LISTING ALL SCHEMAS;
SELECT schema_name FROM INFORMATION_SCHEMA. SCHEMATA

    --b. VIEWING DETAILS OF A SCHEMA;
SELECT * FROM INFORMATION_SCHEMA. SCHEMATA WHERE schema_name = 'public';


--4. INFORMATION_SCHEMA.TRIGGERS

    --a. LISTING ALL TRIGGERS FOR A SPECIFIC TABLE;
SELECT trigger_name, event_object_table, action_timing, action_orientation, action_statement
FROM INFORMATION_SCHEMA.TRIGGERS
WHERE event_object_table = 'titanic';
